//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty_Salon.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beauty_Salon.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string ActiveFeminine {
            get {
                return ResourceManager.GetString("ActiveFeminine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Categoría.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Servicio.
        /// </summary>
        internal static string AddService {
            get {
                return ResourceManager.GetString("AddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        internal static string AgendaTitle {
            get {
                return ResourceManager.GetString("AgendaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Salon.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de citas.
        /// </summary>
        internal static string AppointmentHistory {
            get {
                return ResourceManager.GetString("AppointmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: ${0} · {1} min.
        /// </summary>
        internal static string AppointmentTotalFormat {
            get {
                return ResourceManager.GetString("AppointmentTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promedio por cita.
        /// </summary>
        internal static string AveragePerAppointment {
            get {
                return ResourceManager.GetString("AveragePerAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día libre.
        /// </summary>
        internal static string BlockDayOff {
            get {
                return ResourceManager.GetString("BlockDayOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almuerzo.
        /// </summary>
        internal static string BlockLunch {
            get {
                return ResourceManager.GetString("BlockLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reunión.
        /// </summary>
        internal static string BlockMeeting {
            get {
                return ResourceManager.GetString("BlockMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        internal static string BlockOther {
            get {
                return ResourceManager.GetString("BlockOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No disponible.
        /// </summary>
        internal static string BlockUnavailable {
            get {
                return ResourceManager.GetString("BlockUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacaciones.
        /// </summary>
        internal static string BlockVacation {
            get {
                return ResourceManager.GetString("BlockVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas más ocupadas.
        /// </summary>
        internal static string BusiestHours {
            get {
                return ResourceManager.GetString("BusiestHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llamar.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar cita.
        /// </summary>
        internal static string CancelAppointmentAction {
            get {
                return ResourceManager.GetString("CancelAppointmentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelaciones.
        /// </summary>
        internal static string Cancellations {
            get {
                return ResourceManager.GetString("Cancellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo (opcional):.
        /// </summary>
        internal static string CancelReasonPrompt {
            get {
                return ResourceManager.GetString("CancelReasonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo.
        /// </summary>
        internal static string CatalogTitle {
            get {
                return ResourceManager.GetString("CatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color (para el calendario).
        /// </summary>
        internal static string CategoryColorLabel {
            get {
                return ResourceManager.GetString("CategoryColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio cobrado.
        /// </summary>
        internal static string ChargedPriceLabel {
            get {
                return ResourceManager.GetString("ChargedPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar selección.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de cliente.
        /// </summary>
        internal static string ClientDetailTitle {
            get {
                return ResourceManager.GetString("ClientDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string ClientLabel {
            get {
                return ResourceManager.GetString("ClientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string ClientsTitle {
            get {
                return ResourceManager.GetString("ClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color (opcional).
        /// </summary>
        internal static string ColorOptionalLabel {
            get {
                return ResourceManager.GetString("ColorOptionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citas finalizadas.
        /// </summary>
        internal static string CompletedAppointments {
            get {
                return ResourceManager.GetString("CompletedAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        internal static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora.
        /// </summary>
        internal static string DateAndTimeLabel {
            get {
                return ResourceManager.GetString("DateAndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de fecha.
        /// </summary>
        internal static string DateFormatLabel {
            get {
                return ResourceManager.GetString("DateFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        internal static string DiscountLabel {
            get {
                return ResourceManager.GetString("DiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración (minutos).
        /// </summary>
        internal static string DurationMinutesLabel {
            get {
                return ResourceManager.GetString("DurationMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishLabel {
            get {
                return ResourceManager.GetString("EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorito.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        internal static string FinishAction {
            get {
                return ResourceManager.GetString("FinishAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar cita.
        /// </summary>
        internal static string FinishAppointmentTitle {
            get {
                return ResourceManager.GetString("FinishAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes inactivos (60+ días).
        /// </summary>
        internal static string InactiveClients {
            get {
                return ResourceManager.GetString("InactiveClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conozco la fecha de nacimiento.
        /// </summary>
        internal static string KnowsDateOfBirth {
            get {
                return ResourceManager.GetString("KnowsDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última visita.
        /// </summary>
        internal static string LastVisit {
            get {
                return ResourceManager.GetString("LastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tus credenciales.
        /// </summary>
        internal static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva cita.
        /// </summary>
        internal static string NewAppointmentTitle {
            get {
                return ResourceManager.GetString("NewAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes nuevos.
        /// </summary>
        internal static string NewClients {
            get {
                return ResourceManager.GetString("NewClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva fecha.
        /// </summary>
        internal static string NewDateLabel {
            get {
                return ResourceManager.GetString("NewDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva hora.
        /// </summary>
        internal static string NewTimeLabel {
            get {
                return ResourceManager.GetString("NewTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No asistió.
        /// </summary>
        internal static string NoShowAction {
            get {
                return ResourceManager.GetString("NoShowAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordatorios de citas.
        /// </summary>
        internal static string NotificationRulesLabel {
            get {
                return ResourceManager.GetString("NotificationRulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcional.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de pago.
        /// </summary>
        internal static string PaymentMethodLabel {
            get {
                return ResourceManager.GetString("PaymentMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métodos de pago.
        /// </summary>
        internal static string PaymentMethodsTitle {
            get {
                return ResourceManager.GetString("PaymentMethodsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        internal static string PaymentsTabTitle {
            get {
                return ResourceManager.GetString("PaymentsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        internal static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reagendar.
        /// </summary>
        internal static string RescheduleAction {
            get {
                return ResourceManager.GetString("RescheduleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reagendar cita.
        /// </summary>
        internal static string RescheduleTitle {
            get {
                return ResourceManager.GetString("RescheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos.
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos por método de pago.
        /// </summary>
        internal static string RevenueByPaymentMethod {
            get {
                return ResourceManager.GetString("RevenueByPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUT.
        /// </summary>
        internal static string Rut {
            get {
                return ResourceManager.GetString("Rut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cita.
        /// </summary>
        internal static string SaveAppointment {
            get {
                return ResourceManager.GetString("SaveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por nombre, teléfono o RUT.
        /// </summary>
        internal static string SearchClientListPlaceholder {
            get {
                return ResourceManager.GetString("SearchClientListPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar cliente por nombre, teléfono o RUT.
        /// </summary>
        internal static string SearchClientPlaceholder {
            get {
                return ResourceManager.GetString("SearchClientPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionado: RUT {0}.
        /// </summary>
        internal static string SelectedClientFormat {
            get {
                return ResourceManager.GetString("SelectedClientFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        internal static string ServicesLabel {
            get {
                return ResourceManager.GetString("ServicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        internal static string SortOrderLabel {
            get {
                return ResourceManager.GetString("SortOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string SpanishLabel {
            get {
                return ResourceManager.GetString("SpanishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string StartAction {
            get {
                return ResourceManager.GetString("StartAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservada.
        /// </summary>
        internal static string StatusBooked {
            get {
                return ResourceManager.GetString("StatusBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        internal static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada.
        /// </summary>
        internal static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmada.
        /// </summary>
        internal static string StatusConfirmed {
            get {
                return ResourceManager.GetString("StatusConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En progreso.
        /// </summary>
        internal static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio sugerido.
        /// </summary>
        internal static string SuggestedPriceLabel {
            get {
                return ResourceManager.GetString("SuggestedPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscuro.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de hora.
        /// </summary>
        internal static string TimeFormatLabel {
            get {
                return ResourceManager.GetString("TimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propina.
        /// </summary>
        internal static string TipLabel {
            get {
                return ResourceManager.GetString("TipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        internal static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías más usadas.
        /// </summary>
        internal static string TopCategories {
            get {
                return ResourceManager.GetString("TopCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top clientes.
        /// </summary>
        internal static string TopClients {
            get {
                return ResourceManager.GetString("TopClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios más vendidos.
        /// </summary>
        internal static string TopServices {
            get {
                return ResourceManager.GetString("TopServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total gastado.
        /// </summary>
        internal static string TotalSpent {
            get {
                return ResourceManager.GetString("TotalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitas.
        /// </summary>
        internal static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        internal static string WhatsAppLabel {
            get {
                return ResourceManager.GetString("WhatsAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario laboral.
        /// </summary>
        internal static string WorkingHoursLabel {
            get {
                return ResourceManager.GetString("WorkingHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
